### ISSUE TITLE
Download quota exceeded for the synthetic data zip files in google drive

### ISSUE THREAD

**Issue by darshanasalvi** [ylabbe/cosypose#11]
Hello,
I am interested in downloading the synthetic data generated for this project. I tried using the download script as well as the link directly and got the message "Download quota exceeded for this file, so you can't download it at this time".

Both t-less and ycbv have this message. I waited 24 hours to see if the message would disappear - in case that google reset the download quota for the files - but to no avail.

Could you make it available another way? Is there a way to reset the google file download quota as owners?

Thanks!

**Comment by ylabbe** [comment]
Hi,

Have you tried to download the file manually using your google drive account ? E.g. using this [link](https://drive.google.com/file/d/12cHWnaQyuCXUkuNclQyu5dpYQuJzzxfk/view?usp=sharing).

If it doesn't work, I may be able to find a temporary solution.

Otherwise please note that you can use the PBR images from the BOP challenge, the models trained on the datasets provided with the BOP challenge perform better than those trained using my synthetic images and reported in the paper.

**Comment by Hao-HUST** [comment]
Hi, thanks for sharing.

Follow your advice, I try to manually download the zip file. But, the size of the synthetic dataset is too large, and it is difficult to continue downloading if it is stopped (Breakpoint continuation seems not to support by google drive).  

Do you have any suggestions about that?

**Comment by ylabbe** [comment]
I have uploaded them somewhere, else but I dont know for how long they will remain available: [T-LESS](https://www.rocq.inria.fr/cluster-willow/ylabbe/public/tless-1M.zip) [YCB-V](https://www.rocq.inria.fr/cluster-willow/ylabbe/public/ycbv-1M.zip)

Otherwise, I strongly encourage you to use the PBR synthetic datasets instead, as the models trained on these photorealistic images have better performance.

**Comment by ylabbe** [comment]
I have uploaded them somewhere else but I don't know how long these links will remain available: [YCB-V](https://www.rocq.inria.fr/cluster-willow/ylabbe/public/ycbv-1M.zip) [T-LESS](https://www.rocq.inria.fr/cluster-willow/ylabbe/public/tless-1M.zip)

Otherwise, I strongly encourage you to use the PBR synthetic images instead. The datasets are smaller and the models trained on these photorealistic images have better performance as reported in [this paper](https://arxiv.org/abs/2009.07378).

**Comment by Hao-HUST** [comment]
Great! Thanks a lot!

**Comment by darshanasalvi** [comment]
Thanks for upload!
