### ISSUE TITLE
Any results on the entire test dataset of YCB-Video?

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [ylabbe/cosypose#12]
Hi, thanks for your impressive work. I have downloaded the YCB-Video results via the following command. It seems that the pose estimation results are only evaluated on BOP test dataset. Is there any results on the entire YCB-Video test dataset?
```python
 python -m cosypose.scripts.download --result_id=ycbv-n_views=1--5154971130
```

**Comment by ylabbe** [comment]
Hi, thanks for your interest in the work!

These results are on the 2949 keyframes of the test set that are used in PoseCNN/DeepIM. In the BOP challenge, a different subset of the full test set is used. The BOP organizers have manually selected images that have high-quality ground truth annotations.

To respond to your question: no, I don't have results on the entire YCB-Video dataset but (i) I am not sure there are people reporting on the entire test set, and (ii) it may not be a good idea because some ground truth annotations are noisy. Running the method on the full test set should however be simple using the provided code.

**Comment by Lynne-Zheng-Linfang** [comment]
Thank you for your reply. I am trying to run the method on the full test set by simply modify the `ds_name` from `ycbv.test.keyframes` to `ycbv.test`  in  `run_cosypose_eval.py` as the following code. Should I do any other modifications? Thanks again.
```python
#run_cosypose_eval.py

    if args.config == 'tless-siso':
        ds_name = 'tless.primesense.test'
        assert n_views == 1
    elif args.config == 'tless-vivo':
        ds_name = 'tless.primesense.test.bop19'
    elif args.config == 'ycbv':
        ds_name = 'ycbv.test'   
        # ds_name = 'ycbv.test.keyframes'
    else:
        raise ValueError(args.config)

```

**Comment by ylabbe** [comment]
This script uses PoseCNN detections which are only available on the keyframes if I remember correctly so it won't work. You could try to use the detections from the MaskRCNN models I trained for the BOP challenge, see `run_bop_inference.py` script.

**Comment by Lynne-Zheng-Linfang** [comment]
Hi, I have checked with the `run_bop_inference.py` and did the following modifications. Are the modifications right? I am trying to use CosyPose as the initialization method for my pose tracking approach, that's why I needed the results on the entire YCB-Video dataset. Thanks again.
I) 
```python
# run_bop_inference.py
    if args.n_views > 1:
        #ds_names = ['hb', 'tless', 'ycbv']
        ds_names = ['ycbv']
    else:
        # ds_names = ['hb', 'icbin', 'itodd', 'lmo', 'tless', 'tudl', 'ycbv']
        ds_names = ['ycbv']
```
ii) Change the `test_targets_bop19.json` file so that all the test images are included.
iii) run with '' python -m cosypose.scripts.run_bop_inference --config bop-synt+real'

**Comment by ylabbe** [comment]
I think it should work yes

**Comment by Lynne-Zheng-Linfang** [comment]
Thank you!
