### ISSUE TITLE
linemod dataset

### ISSUE THREAD

**Issue by naaths** [ylabbe/cosypose#5]
Hello, may I ask, can this code directly train and evaluate the linemod dataset? Thank you

**Comment by ylabbe** [comment]
Hi,

We provide models trained on the linemod synthetic PBR images and evaluated them on the Linemod-Occluded dataset for the BOP challenge. The code for training and evaluation of these models is available in this repository (see section on bop20 challenge). I haven't evaluated these models on Linemod but it is very easy to modify bop20 inference and evaluation scripts to evaluate on this dataset. 

Note however that this wouldn't be a fair comparison with most other works that use parts of real linemod images for training whereas our models are only trained on PBR synthetic images. I did not train models on the real linemod images because there is no official training split with real images for Linemod on the [BOP website](https://bop.felk.cvut.cz/datasets/).

I may train and evaluate our approach on the linemod training/test splits commonly used by other works in a future version of the paper.

**Comment by surakmir** [comment]
Hello, I'm trying to train pose using this command: runjob --ngpus=32 python -m cosypose.scripts.run_pose_training --config bop-lmo-pbr-coarse, but it doesnt work. I'm gettig ValueError: Cannot find valid image in the dataset. I have downloaded full linemod dataset, although I'm not using full dataset, only first 10 folders in train_pbr (probably the cause, but I cant find the settings restricting/demanding full dataset in code). 
My goal is to train your network on linemode dataset, but with custom models. Would that be possible?
