### ISSUE TITLE
BOP evaluation metrics

### ISSUE THREAD

**Issue by GodZarathustra** [ylabbe/cosypose#7]
Hello authors:
I have read your paper and look through your released code. I find that you only reported the VSD metric when you evaluate T-LESS dataset, but didn't find any report taking the BOP metric of MSSD and MSPD. However, CosyPose reports the highest record on BOP Challenge 2020 (https://bop.felk.cvut.cz/media/bop_challenge_2020_results.pdf), and BOP Challenge takes the average recall of VSD, MSSD, MSPD as the final evaluation metric. 
So does your code support MSSD and MSPD? Can you show me some details about the results on MSSD and MSPD?
Thanks!

**Comment by ylabbe** [comment]
In the paper we reported evsd<0.3 on the full T-LESS dataset to provide a fair comparison with prior works that only reported this metric (AAE, Pix2pose). It is possible to compute the other metrics like in the BOP challenge using the [bop toolkit](https://github.com/thodan/bop_toolkit). I provide the csv files with  single-view and multi-view predictions that can directly be plugged into this evaluation code for VSD, MSSD and MSPD. If you want to compare with our complete approach reported in the BOP challenge (also including detection with our Mask-RCNN models whereas we use Pix2pose's detections in the paper) you can use directly the numbers that are on the BOP leaderboard.

**Comment by GodZarathustra** [comment]
> In the paper we reported evsd<0.3 on the full T-LESS dataset to provide a fair comparison with prior works that only reported this metric (AAE, Pix2pose). It is possible to compute the other metrics like in the BOP challenge using the [bop toolkit](https://github.com/thodan/bop_toolkit). I provide the csv files with single-view and multi-view predictions that can directly be plugged into this evaluation code for VSD, MSSD and MSPD. If you want to compare with our complete approach reported in the BOP challenge (also including detection with our Mask-RCNN models whereas we use Pix2pose's detections in the paper) you can use directly the numbers that are on the BOP leaderboard.

Thanks for your reply, that helps. But I have some other questions about your paper : 
1) Can you please explain why the performance of your method dropped after performing ICP refinement on T-LESS dataset on the BOP leaderboard?
2) According to the BOP leaderboard, on T-LESS dataset, the AR score of your method is more than 0.7(with single-view, w/o ICP), and in your paper, the AR score is 62.6, which means the MSSD and MSPD scores are higher than the VSD score. Do you have some experimental results（numbers）that shows the effectivity of the tricks that you have mentioned in your paper to handle symmetry problem? i.e. do you know how much performance improvement that the symmetric disentangled loss could bring to your method?

**Comment by ylabbe** [comment]
> 1. Can you please explain why the performance of your method dropped after performing ICP refinement on T-LESS dataset on the BOP leaderboard?

I am not really sure why and mention this as an issue of our ICP implementation in the BOP section. Qualitatively, there is a slight misalignement of the objects after ICP on T-LESS. I discussed with @MartinSmeyer about it and he mentionned to me that he had observed misalignment issues between the RGB and depth sensors on T-LESS but I don't think there is a clear explanation right now. I am not interested in spending more time to investigate this right now as I mostly work with only RGB. If you are interested in investigating this issue, I would say a good starting point would be to try to run ICP on the ground truth poses to see if there is a problem in the depth data provided.

> 2. According to the BOP leaderboard, on T-LESS dataset, the AR score of your method is more than 0.7(with single-view, w/o ICP), and in your paper, the AR score is 62.6, which means the MSSD and MSPD scores are higher than the VSD score.

I don't see issues with MSPD and MSSD being higher than VSD score, these are really different metrics and quickly looking at the results it seems that MSPD and MSSD are typically higher than VSD (on multiple datasets, for other methods too). I also think it is normal that the AR score is higher on the BOP challenge compared to what's in the paper because the BOP models are trained on PBR images instead of my opengl synthetic images, and the detector is also trained on the PBR images which leads to higher detection accuracy compared to the retinanet model trained by Pix2Pose on lower quality images. I also changed the initialization method of the coarse pose estimation model for the BOP challenge as described in the BOP section of the readme.

> Do you have some experimental results（numbers）that shows the effectivity of the tricks that you have mentioned in your paper to handle symmetry problem? i.e. do you know how much performance improvement that the symmetric disentangled loss could bring to your method ?

I do not have these numbers right now. I think what would be interesting is to verify that enumerating symmetries in the loss improves MSSD and MSPD vs not enumerating the symmetries at all. I have a plan to study the loss more in details but I can't guarantee you that I will provide these results here soon.

**Comment by GodZarathustra** [comment]
> > 1. Can you please explain why the performance of your method dropped after performing ICP refinement on T-LESS dataset on the BOP leaderboard?
> 
> I am not really sure why and mention this as an issue of our ICP implementation in the BOP section. Qualitatively, there is a slight misalignement of the objects after ICP on T-LESS. I discussed with @MartinSmeyer about it and he mentionned to me that he had observed misalignment issues between the RGB and depth sensors on T-LESS but I don't think there is a clear explanation right now. I am not interested in spending more time to investigate this right now as I mostly work with only RGB. If you are interested in investigating this issue, I would say a good starting point would be to try to run ICP on the ground truth poses to see if there is a problem in the depth data provided.
> 
> > 1. According to the BOP leaderboard, on T-LESS dataset, the AR score of your method is more than 0.7(with single-view, w/o ICP), and in your paper, the AR score is 62.6, which means the MSSD and MSPD scores are higher than the VSD score.
> 
> I don't see issues with MSPD and MSSD being higher than VSD score, these are really different metrics and quickly looking at the results it seems that MSPD and MSSD are typically higher than VSD (on multiple datasets, for other methods too). I also think it is normal that the AR score is higher on the BOP challenge compared to what's in the paper because the BOP models are trained on PBR images instead of my opengl synthetic images, and the detector is also trained on the PBR images which leads to higher detection accuracy compared to the retinanet model trained by Pix2Pose on lower quality images. I also improved the initialization method of the coarse pose estimation model for the BOP challenge as described in the BOP section of the readme.
> 
> > Do you have some experimental results（numbers）that shows the effectivity of the tricks that you have mentioned in your paper to handle symmetry problem? i.e. do you know how much performance improvement that the symmetric disentangled loss could bring to your method ?
> 
> I do not have these numbers right now. I think what would be interesting is to verify that enumerating symmetries in the loss improves MSSD and MSPD vs not enumerating the symmetries at all. I have a plan to study the loss more in details but I can't guarantee you that I will provide these results here soon.

Okay. Thank you very much, and I am also evaluating the symmetry loss on my method, if you have any results on about the symmetry loss on your method, please share with me  : )
